const words = [
    { "russian": "Привет", "transliteration": "Privet", "hebrew": "שלום" },
    { "russian": "Спасибо", "transliteration": "Spasibo", "hebrew": "תודה" },
    { "russian": "Пожалуйста", "transliteration": "Pozhaluysta", "hebrew": "בבקשה" },
    { "russian": "Да", "transliteration": "Da", "hebrew": "כן" },
    { "russian": "Нет", "transliteration": "Net", "hebrew": "לא" },
    { "russian": "Здравствуйте", "transliteration": "Zdravstvuyte", "hebrew": "שלום (רשמי)" },
    { "russian": "Доброе утро", "transliteration": "Dobroe utro", "hebrew": "בוקר טוב" },
    { "russian": "Добрый день", "transliteration": "Dobry den", "hebrew": "צהריים טובים" },
    { "russian": "Добрый вечер", "transliteration": "Dobry vecher", "hebrew": "ערב טוב" },
    { "russian": "Спокойной ночи", "transliteration": "Spokoynoy nochi", "hebrew": "לילה טוב" },
    { "russian": "Как дела?", "transliteration": "Kak dela?", "hebrew": "מה שלומך?" },
    { "russian": "Хорошо", "transliteration": "Khorosho", "hebrew": "טוב" },
    { "russian": "Плохо", "transliteration": "Plokho", "hebrew": "רע" },
    { "russian": "Извините", "transliteration": "Izvinite", "hebrew": "סליחה" },
    { "russian": "Я не понимаю", "transliteration": "Ya ne ponimayu", "hebrew": "אני לא מבין" },
    { "russian": "Где туалет?", "transliteration": "Gde tualet?", "hebrew": "איפה השירותים?" },
    { "russian": "Сколько это стоит?", "transliteration": "Skolko eto stoit?", "hebrew": "כמה זה עולה?" },
    { "russian": "Вода", "transliteration": "Voda", "hebrew": "מים" },
    { "russian": "Еда", "transliteration": "Yeda", "hebrew": "אוכל" },
    { "russian": "Друг", "transliteration": "Drug", "hebrew": "חבר" },
    { "russian": "Семья", "transliteration": "Semya", "hebrew": "משפחה" },
    { "russian": "Дом", "transliteration": "Dom", "hebrew": "בית" },
    { "russian": "Работа", "transliteration": "Rabota", "hebrew": "עבודה" },
    { "russian": "Кошка", "transliteration": "Koshka", "hebrew": "חתול" },
    { "russian": "Собака", "transliteration": "Sobaka", "hebrew": "כלב" },
    { "russian": "Кофе", "transliteration": "Kofe", "hebrew": "קפה" },
    { "russian": "Чай", "transliteration": "Chay", "hebrew": "תה" },
    { "russian": "Пиво", "transliteration": "Pivo", "hebrew": "בירה" },
    { "russian": "Вино", "transliteration": "Vino", "hebrew": "יין" },
    { "russian": "Счет, пожалуйста", "transliteration": "Schet, pozhaluysta", "hebrew": "חשבון, בבקשה" },
    { "russian": "Меню", "transliteration": "Menyu", "hebrew": "תפריט" },
    { "russian": "Завтрак", "transliteration": "Zavtrak", "hebrew": "ארוחת בוקר" },
    { "russian": "Обед", "transliteration": "Obed", "hebrew": "ארוחת צהריים" },
    { "russian": "Ужин", "transliteration": "Uzhin", "hebrew": "ארוחת ערב" },
    { "russian": "Вкусно", "transliteration": "Vkusno", "hebrew": "טעים" },
    { "russian": "Хлеб", "transliteration": "Khleb", "hebrew": "לחם" },
    { "russian": "Молоко", "transliteration": "Moloko", "hebrew": "חלב" },
    { "russian": "Сахар", "transliteration": "Sakhar", "hebrew": "סוכר" },
    { "russian": "Соль", "transliteration": "Sol", "hebrew": "מלח" },
    { "russian": "Мясо", "transliteration": "Myaso", "hebrew": "בשר" },
    { "russian": "Рыба", "transliteration": "Ryba", "hebrew": "דג" },
    { "russian": "Овощи", "transliteration": "Ovoshchi", "hebrew": "ירקות" },
    { "russian": "Фрукты", "transliteration": "Frukty", "hebrew": "פירות" },
    { "russian": "Магазин", "transliteration": "Magazin", "hebrew": "חנות" },
    { "russian": "Деньги", "transliteration": "Dengi", "hebrew": "כסף" },
    { "russian": "Дорого", "transliteration": "Dorogo", "hebrew": "יקר" },
    { "russian": "Дешево", "transliteration": "Deshevo", "hebrew": "זול" },
    { "russian": "Открыто", "transliteration": "Otkryto", "hebrew": "פתוח" },
    { "russian": "Закрыто", "transliteration": "Zakryto", "hebrew": "סגור" },
    { "russian": "Выход", "transliteration": "Vykhod", "hebrew": "יציאה" },
    { "russian": "Вход", "transliteration": "Vkhod", "hebrew": "כניסה" },
    { "russian": "Мужчина", "transliteration": "Muzhchina", "hebrew": "גבר" },
    { "russian": "Женщина", "transliteration": "Zhenshchina", "hebrew": "אישה" },
    { "russian": "Ребенок", "transliteration": "Rebenok", "hebrew": "ילד" },
    { "russian": "Любовь", "transliteration": "Lyubov", "hebrew": "אהבה" },
    { "russian": "Счастье", "transliteration": "Schastye", "hebrew": "אושר" },
    { "russian": "Время", "transliteration": "Vremya", "hebrew": "זמן" },
    { "russian": "Сегодня", "transliteration": "Segodnya", "hebrew": "היום" },
    { "russian": "Завтра", "transliteration": "Zavtra", "hebrew": "מחר" },
    { "russian": "Вчера", "transliteration": "Vchera", "hebrew": "אתמול" },
    { "russian": "Сейчас", "transliteration": "Seychas", "hebrew": "עכשיו" },
    { "russian": "Потом", "transliteration": "Potom", "hebrew": "אחר כך" },
    { "russian": "День", "transliteration": "Den", "hebrew": "יום" },
    { "russian": "Ночь", "transliteration": "Noch", "hebrew": "לילה" },
    { "russian": "Неделя", "transliteration": "Nedelya", "hebrew": "שבוע" },
    { "russian": "Месяц", "transliteration": "Mesyats", "hebrew": "חודש" },
    { "russian": "Год", "transliteration": "God", "hebrew": "שנה" },
    { "russian": "Понедельник", "transliteration": "Ponedelnik", "hebrew": "יום שני" },
    { "russian": "Вторник", "transliteration": "Vtornik", "hebrew": "יום שלישי" },
    { "russian": "Среда", "transliteration": "Sreda", "hebrew": "יום רביעי" },
    { "russian": "Четверг", "transliteration": "Chetverg", "hebrew": "יום חמישי" },
    { "russian": "Пятница", "transliteration": "Pyatnitsa", "hebrew": "יום שישי" },
    { "russian": "Суббота", "transliteration": "Subbota", "hebrew": "שבת" },
    { "russian": "Воскресенье", "transliteration": "Voskresenye", "hebrew": "יום ראשון" },
    { "russian": "Один", "transliteration": "Odin", "hebrew": "אחד" },
    { "russian": "Два", "transliteration": "Dva", "hebrew": "שתיים" },
    { "russian": "Три", "transliteration": "Tri", "hebrew": "שלוש" },
    { "russian": "Четыре", "transliteration": "Chetyre", "hebrew": "ארבע" },
    { "russian": "Пять", "transliteration": "Pyat", "hebrew": "חמש" },
    { "russian": "Шесть", "transliteration": "Shest", "hebrew": "שש" },
    { "russian": "Семь", "transliteration": "Sem", "hebrew": "שבע" },
    { "russian": "Восемь", "transliteration": "Vosem", "hebrew": "שמונה" },
    { "russian": "Девять", "transliteration": "Devyat", "hebrew": "תשע" },
    { "russian": "Десять", "transliteration": "Desyat", "hebrew": "עשר" },
    { "russian": "Сто", "transliteration": "Sto", "hebrew": "מאה" },
    { "russian": "Тысяча", "transliteration": "Tysyacha", "hebrew": "אלף" },
    { "russian": "Кто?", "transliteration": "Kto?", "hebrew": "מי?" },
    { "russian": "Что?", "transliteration": "Chto?", "hebrew": "מה?" },
    { "russian": "Почему?", "transliteration": "Pochemu?", "hebrew": "למה?" },
    { "russian": "Когда?", "transliteration": "Kogda?", "hebrew": "מתי?" },
    { "russian": "Как?", "transliteration": "Kak?", "hebrew": "איך?" },
    { "russian": "Здесь", "transliteration": "Zdes", "hebrew": "כאן" },
    { "russian": "Там", "transliteration": "Tam", "hebrew": "שם" },
    { "russian": "Этот", "transliteration": "Etot", "hebrew": "זה" },
    { "russian": "Тот", "transliteration": "Tot", "hebrew": "ההוא" },
    { "russian": "Мой", "transliteration": "Moy", "hebrew": "שלי" },
    { "russian": "Твой", "transliteration": "Tvoy", "hebrew": "שלך" },
    { "russian": "Наш", "transliteration": "Nash", "hebrew": "שלנו" },
    { "russian": "Их", "transliteration": "Ikh", "hebrew": "שלהם" },
    { "russian": "Большой", "transliteration": "Bolshoy", "hebrew": "גדול" },
    { "russian": "Маленький", "transliteration": "Malenky", "hebrew": "קטן" },
    { "russian": "Новый", "transliteration": "Novy", "hebrew": "חדש" },
    { "russian": "Старый", "transliteration": "Stary", "hebrew": "ישן" },
    { "russian": "Красный", "transliteration": "Krasny", "hebrew": "אדום" },
    { "russian": "Синий", "transliteration": "Siniy", "hebrew": "כחול" },
    { "russian": "Зеленый", "transliteration": "Zeleny", "hebrew": "ירוק" },
    { "russian": "Черный", "transliteration": "Cherny", "hebrew": "שחור" },
    { "russian": "Белый", "transliteration": "Bely", "hebrew": "לבן" },
    { "russian": "Улица", "transliteration": "Ulitsa", "hebrew": "רחוב" },
    { "russian": "Город", "transliteration": "Gorod", "hebrew": "עיר" },
    { "russian": "Страна", "transliteration": "Strana", "hebrew": "מדינה" },
    { "russian": "Мир", "transliteration": "Mir", "hebrew": "עולם" },
    { "russian": "Человек", "transliteration": "Chelovek", "hebrew": "אדם" },
    { "russian": "Люди", "transliteration": "Lyudi", "hebrew": "אנשים" },
    { "russian": "Слушать", "transliteration": "Slushat", "hebrew": "להקשיב" },
    { "russian": "Говорить", "transliteration": "Govorit", "hebrew": "לדבר" },
    { "russian": "Читать", "transliteration": "Chitat", "hebrew": "לקרוא" },
    { "russian": "Писать", "transliteration": "Pisat", "hebrew": "לכתוב" },
    { "russian": "Идти", "transliteration": "Idti", "hebrew": "ללכת" },
    { "russian": "Делать", "transliteration": "Delat", "hebrew": "לעשות" },
    { "russian": "Думать", "transliteration": "Dumat", "hebrew": "לחשוב" },
    { "russian": "Знать", "transliteration": "Znat", "hebrew": "לדעת" },
    { "russian": "Смотреть", "transliteration": "Smotret", "hebrew": "להסתכל" },
    { "russian": "Видеть", "transliteration": "Videt", "hebrew": "לראות" },
    { "russian": "Хотеть", "transliteration": "Khotet", "hebrew": "לרצות" },
    { "russian": "Мочь", "transliteration": "Moch", "hebrew": "יכול" },
    { "russian": "Любить", "transliteration": "Lyubit", "hebrew": "לאהוב" },
    { "russian": "Жить", "transliteration": "Zhit", "hebrew": "לחיות" },
    { "russian": "Работать", "transliteration": "Rabotat", "hebrew": "לעבוד" },
    { "russian": "Играть", "transliteration": "Igrat", "hebrew": "לשחק" },
    { "russian": "Спать", "transliteration": "Spat", "hebrew": "לישון" },
    { "russian": "Есть", "transliteration": "Yest", "hebrew": "לאכול" },
    { "russian": "Пить", "transliteration": "Pit", "hebrew": "לשתות" },
    { "russian": "Купить", "transliteration": "Kupit", "hebrew": "לקנות" },
    { "russian": "Ждать", "transliteration": "Zhdat", "hebrew": "לחכות" },
    { "russian": "Понимать", "transliteration": "Ponimat", "hebrew": "להבין" },
    { "russian": "Помогать", "transliteration": "Pomogat", "hebrew": "לעזור" },
    { "russian": "Брать", "transliteration": "Brat", "hebrew": "לקחת" },
    { "russian": "Давать", "transliteration": "Davat", "hebrew": "לתת" },
    { "russian": "Звонить", "transliteration": "Zvonit", "hebrew": "להתקשר" },
    { "russian": "Встречать", "transliteration": "Vstrechat", "hebrew": "לפגוש" },
    { "russian": "Учить", "transliteration": "Uchit", "hebrew": "ללמוד" },
    { "russian": "Помнить", "transliteration": "Pomnit", "hebrew": "לזכור" },
    { "russian": "Забыть", "transliteration": "Zabyt", "hebrew": "לשכוח" },
    { "russian": "Начинать", "transliteration": "Nachinat", "hebrew": "להתחיל" },
    { "russian": "Заканчивать", "transliteration": "Zakanchivat", "hebrew": "לסיים" },
    { "russian": "Открывать", "transliteration": "Otkryvat", "hebrew": "לפתוח" },
    { "russian": "Закрывать", "transliteration": "Zakryvat", "hebrew": "לסגור" },
    { "russian": "Искать", "transliteration": "Iskat", "hebrew": "לחפש" },
    { "russian": "Находить", "transliteration": "Nakhodit", "hebrew": "למצוא" },
    { "russian": "Терять", "transliteration": "Teryat", "hebrew": "לאבד" },
    { "russian": "Спрашивать", "transliteration": "Sprashivat", "hebrew": "לשאול" },
    { "russian": "Отвечать", "transliteration": "Otvechat", "hebrew": "לענות" },
    { "russian": "Стоять", "transliteration": "Stoyat", "hebrew": "לעמוד" },
    { "russian": "Сидеть", "transliteration": "Sidet", "hebrew": "לשבת" },
    { "russian": "Лежать", "transliteration": "Lezhat", "hebrew": "לשכב" },
    { "russian": "Бежать", "transliteration": "Bezhat", "hebrew": "לרוץ" },
    { "russian": "Прыгать", "transliteration": "Prygat", "hebrew": "לקפוץ" },
    { "russian": "Танцевать", "transliteration": "Tantsevat", "hebrew": "לרקוד" },
    { "russian": "Петь", "transliteration": "Pet", "hebrew": "לשיר" },
    { "russian": "Улыбаться", "transliteration": "Ulybatsya", "hebrew": "לחייך" },
    { "russian": "Смеяться", "transliteration": "Smeyatsya", "hebrew": "לצחוק" },
    { "russian": "Плакать", "transliteration": "Plakat", "hebrew": "לבכות" },
    { "russian": "Бояться", "transliteration": "Boyatsya", "hebrew": "לפחד" },
    { "russian": "Надеяться", "transliteration": "Nadeyatsya", "hebrew": "לקוות" },
    { "russian": "Верить", "transliteration": "Verit", "hebrew": "להאמין" },
    { "russian": "Врач", "transliteration": "Vrach", "hebrew": "רופא" },
    { "russian": "Учитель", "transliteration": "Uchitel", "hebrew": "מורה" },
    { "russian": "Студент", "transliteration": "Student", "hebrew": "סטודנט" },
    { "russian": "Школа", "transliteration": "Shkola", "hebrew": "בית ספר" },
    { "russian": "Университет", "transliteration": "Universitet", "hebrew": "אוניברסיטה" },
    { "russian": "Класс", "transliteration": "Klass", "hebrew": "כיתה" },
    { "russian": "Урок", "transliteration": "Urok", "hebrew": "שיעור" },
    { "russian": "Экзамен", "transliteration": "Ekzamen", "hebrew": "מבחן" },
    { "russian": "Карандаш", "transliteration": "Karandash", "hebrew": "עיפרון" },
    { "russian": "Ручка", "transliteration": "Ruchka", "hebrew": "עט" },
    { "russian": "Бумага", "transliteration": "Bumaga", "hebrew": "נייר" },
    { "russian": "Книга", "transliteration": "Kniga", "hebrew": "ספר" },
    { "russian": "Тетрадь", "transliteration": "Tetrad", "hebrew": "מחברת" },
    { "russian": "Словарь", "transliteration": "Slovar", "hebrew": "מילון" },
    { "russian": "Слово", "transliteration": "Slovo", "hebrew": "מילה" },
    { "russian": "Язык", "transliteration": "Yazyk", "hebrew": "שפה" },
    { "russian": "Русский", "transliteration": "Russkiy", "hebrew": "רוסית" },
    { "russian": "Английский", "transliteration": "Angliyskiy", "hebrew": "אנגלית" },
    { "russian": "Иврит", "transliteration": "Ivrit", "hebrew": "עברית" },
    { "russian": "Машина", "transliteration": "Mashina", "hebrew": "מכונית" },
    { "russian": "Автобус", "transliteration": "Avtobus", "hebrew": "אוטובוס" },
    { "russian": "Поезд", "transliteration": "Poezd", "hebrew": "רכבת" },
    { "russian": "Самолет", "transliteration": "Samolet", "hebrew": "מטוס" },
    { "russian": "Такси", "transliteration": "Taksi", "hebrew": "מונית" },
    { "russian": "Велосипед", "transliteration": "Velosiped", "hebrew": "אופניים" },
    { "russian": "Дорога", "transliteration": "Doroga", "hebrew": "דרך" },
    { "russian": "Светофор", "transliteration": "Svetofor", "hebrew": "רמזור" },
    { "russian": "Остановка", "transliteration": "Ostanovka", "hebrew": "תחנה" },
    { "russian": "Билет", "transliteration": "Bilet", "hebrew": "כרטיס" },
    { "russian": "Паспорт", "transliteration": "Pasport", "hebrew": "דרכון" },
    { "russian": "Виза", "transliteration": "Viza", "hebrew": "ויזה" },
    { "russian": "Чемодан", "transliteration": "Chemodan", "hebrew": "מזוודה" },
    { "russian": "Сумка", "transliteration": "Sumka", "hebrew": "תיק" },
    { "russian": "Карта", "transliteration": "Karta", "hebrew": "מפה" },
    { "russian": "Гостиница", "transliteration": "Gostinitsa", "hebrew": "מלון" },
    { "russian": "Комната", "transliteration": "Komnata", "hebrew": "חדר" },
    { "russian": "Ключ", "transliteration": "Klyuch", "hebrew": "מפתח" },
    { "russian": "Кровать", "transliteration": "Krovat", "hebrew": "מיטה" },
    { "russian": "Стол", "transliteration": "Stol", "hebrew": "שולחן" },
    { "russian": "Стул", "transliteration": "Stul", "hebrew": "כיסא" },
    { "russian": "Окно", "transliteration": "Okno", "hebrew": "חלון" },
    { "russian": "Дверь", "transliteration": "Dver", "hebrew": "דלת" },
    { "russian": "Пол", "transliteration": "Pol", "hebrew": "רצפה" },
    { "russian": "Потолок", "transliteration": "Potolok", "hebrew": "תקרה" },
    { "russian": "Стена", "transliteration": "Stena", "hebrew": "קיר" },
    { "russian": "Кухня", "transliteration": "Kukhnya", "hebrew": "מטבח" },
    { "russian": "Ванная", "transliteration": "Vannaya", "hebrew": "אמבטיה" },
    { "russian": "Душ", "transliteration": "Dush", "hebrew": "מקלחת" },
    { "russian": "Мыло", "transliteration": "Mylo", "hebrew": "סבון" },
    { "russian": "Полотенце", "transliteration": "Polotentse", "hebrew": "מגבת" },
    { "russian": "Зеркало", "transliteration": "Zerkalo", "hebrew": "מראה" },
    { "russian": "Одежда", "transliteration": "Odezhda", "hebrew": "בגדים" },
    { "russian": "Рубашка", "transliteration": "Rubashka", "hebrew": "חולצה" },
    { "russian": "Брюки", "transliteration": "Bryuki", "hebrew": "מכנסיים" },
    { "russian": "Платье", "transliteration": "Platye", "hebrew": "שמלה" },
    { "russian": "Юбка", "transliteration": "Yubka", "hebrew": "חצאית" },
    { "russian": "Обувь", "transliteration": "Obuv", "hebrew": "נעליים" },
    { "russian": "Шапка", "transliteration": "Shapka", "hebrew": "כובע" },
    { "russian": "Пальто", "transliteration": "Palto", "hebrew": "מעיל" },
    { "russian": "Цвет", "transliteration": "Tsvet", "hebrew": "צבע" },
    { "russian": "Желтый", "transliteration": "Zhelty", "hebrew": "צהוב" },
    { "russian": "Розовый", "transliteration": "Rozovy", "hebrew": "ורוד" },
    { "russian": "Серый", "transliteration": "Sery", "hebrew": "אפור" },
    { "russian": "Коричневый", "transliteration": "Korichnevy", "hebrew": "חום" },
    { "russian": "Погода", "transliteration": "Pogoda", "hebrew": "מזג אוויר" },
    { "russian": "Солнце", "transliteration": "Solntse", "hebrew": "שמש" },
    { "russian": "Дождь", "transliteration": "Dozhd", "hebrew": "גשם" },
    { "russian": "Снег", "transliteration": "Sneg", "hebrew": "שלג" },
    { "russian": "Ветер", "transliteration": "Veter", "hebrew": "רוח" },
    { "russian": "Облако", "transliteration": "Oblako", "hebrew": "ענן" },
    { "russian": "Тепло", "transliteration": "Teplo", "hebrew": "חם (נעים)" },
    { "russian": "Холодно", "transliteration": "Kholodno", "hebrew": "קר" },
    { "russian": "Жарко", "transliteration": "Zharko", "hebrew": "חם (לוהט)" },
    { "russian": "Лето", "transliteration": "Leto", "hebrew": "קיץ" },
    { "russian": "Зима", "transliteration": "Zima", "hebrew": "חורף" },
    { "russian": "Весна", "transliteration": "Vesna", "hebrew": "אביב" },
    { "russian": "Осень", "transliteration": "Osen", "hebrew": "סתיו" },
    { "russian": "Природа", "transliteration": "Priroda", "hebrew": "טבע" },
    { "russian": "Дерево", "transliteration": "Derevo", "hebrew": "עץ" },
    { "russian": "Цветок", "transliteration": "Tsvetok", "hebrew": "פרח" },
    { "russian": "Море", "transliteration": "More", "hebrew": "ים" },
    { "russian": "Река", "transliteration": "Reka", "hebrew": "נהר" },
    { "russian": "Гора", "transliteration": "Gora", "hebrew": "הר" },
    { "russian": "Лес", "transliteration": "Les", "hebrew": "יער" },
    { "russian": "Животное", "transliteration": "Zhivotnoe", "hebrew": "חיה" },
    { "russian": "Птица", "transliteration": "Ptitsa", "hebrew": "ציפור" },
    { "russian": "Рыба", "transliteration": "Ryba", "hebrew": "דג" },
    { "russian": "Лошадь", "transliteration": "Loshad", "hebrew": "סוס" },
    { "russian": "Корова", "transliteration": "Korova", "hebrew": "פרה" },
    { "russian": "Свинья", "transliteration": "Svinya", "hebrew": "חזיר" },
    { "russian": "Курица", "transliteration": "Kuritsa", "hebrew": "תרנגולת" },
    { "russian": "Яйцо", "transliteration": "Yaytso", "hebrew": "ביצה" },
    { "russian": "Масло", "transliteration": "Maslo", "hebrew": "חמאה" },
    { "russian": "Сыр", "transliteration": "Syr", "hebrew": "גבינה" },
    { "russian": "Картошка", "transliteration": "Kartoshka", "hebrew": "תפוח אדמה" },
    { "russian": "Помидор", "transliteration": "Pomidor", "hebrew": "עגבניה" },
    { "russian": "Огурец", "transliteration": "Ogurets", "hebrew": "מלפפון" },
    { "russian": "Лук", "transliteration": "Luk", "hebrew": "בצל" },
    { "russian": "Чеснок", "transliteration": "Chesnok", "hebrew": "שום" },
    { "russian": "Яблоко", "transliteration": "Yabloko", "hebrew": "תפוח" },
    { "russian": "Банан", "transliteration": "Banan", "hebrew": "בננה" },
    { "russian": "Апельсин", "transliteration": "Apelsin", "hebrew": "תפוז" },
    { "russian": "Лимон", "transliteration": "Limon", "hebrew": "לימון" },
    { "russian": "Торт", "transliteration": "Tort", "hebrew": "עוגה" },
    { "russian": "Шоколад", "transliteration": "Shokolad", "hebrew": "שוקולד" },
    { "russian": "Мороженое", "transliteration": "Morozhenoe", "hebrew": "גלידה" },
    { "russian": "Сок", "transliteration": "Sok", "hebrew": "מיץ" },
    { "russian": "Стакан", "transliteration": "Stakan", "hebrew": "כוס" },
    { "russian": "Чашка", "transliteration": "Chashka", "hebrew": "ספל" },
    { "russian": "Тарелка", "transliteration": "Tarelka", "hebrew": "צלחת" },
    { "russian": "Ложка", "transliteration": "Lozhka", "hebrew": "כף" },
    { "russian": "Вилка", "transliteration": "Vilka", "hebrew": "מזלג" },
    { "russian": "Нож", "transliteration": "Nozh", "hebrew": "סכין" },
    { "russian": "Салфетка", "transliteration": "Salfetka", "hebrew": "מפית" },
    { "russian": "Скатерть", "transliteration": "Skatert", "hebrew": "מפה (לשולחן)" },
    { "russian": "Подарок", "transliteration": "Podarok", "hebrew": "מתנה" },
    { "russian": "Праздник", "transliteration": "Prazdnik", "hebrew": "חג" },
    { "russian": "День рождения", "transliteration": "Den rozhdeniya", "hebrew": "יום הולדת" },
    { "russian": "Новый год", "transliteration": "Novy god", "hebrew": "שנה חדשה" },
    { "russian": "Рождество", "transliteration": "Rozhdestvo", "hebrew": "חג המולד" },
    { "russian": "Пасха", "transliteration": "Paskha", "hebrew": "פסחא" },
    { "russian": "Церковь", "transliteration": "Tserkov", "hebrew": "כנסייה" },
    { "russian": "Бог", "transliteration": "Bog", "hebrew": "אלוהים" },
    { "russian": "Вера", "transliteration": "Vera", "hebrew": "אמונה" },
    { "russian": "Душа", "transliteration": "Dusha", "hebrew": "נשמה" },
    { "russian": "Сердце", "transliteration": "Serdtse", "hebrew": "לב" },
    { "russian": "Голова", "transliteration": "Golova", "hebrew": "ראש" },
    { "russian": "Лицо", "transliteration": "Litso", "hebrew": "פנים" },
    { "russian": "Глаз", "transliteration": "Glaz", "hebrew": "עין" },
    { "russian": "Ухо", "transliteration": "Ukho", "hebrew": "אוזן" },
    { "russian": "Нос", "transliteration": "Nos", "hebrew": "אף" },
    { "russian": "Рот", "transliteration": "Rot", "hebrew": "פה" },
    { "russian": "Зуб", "transliteration": "Zub", "hebrew": "שן" },
    { "russian": "Рука", "transliteration": "Ruka", "hebrew": "יד" },
    { "russian": "Нога", "transliteration": "Noga", "hebrew": "רגל" },
    { "russian": "Палец", "transliteration": "Palets", "hebrew": "אצבע" },
    { "russian": "Живот", "transliteration": "Zhivot", "hebrew": "בטן" },
    { "russian": "Спина", "transliteration": "Spina", "hebrew": "גב" },
    { "russian": "Кровь", "transliteration": "Krov", "hebrew": "דם" },
    { "russian": "Болезнь", "transliteration": "Bolezn", "hebrew": "מחלה" },
    { "russian": "Лекарство", "transliteration": "Lekarstvo", "hebrew": "תרופה" },
    { "russian": "Аптека", "transliteration": "Apteka", "hebrew": "בית מרקחת" },
    { "russian": "Полиция", "transliteration": "Politsiya", "hebrew": "משטרה" },
    { "russian": "Пожар", "transliteration": "Pozhar", "hebrew": "שריפה" },
    { "russian": "Скорая помощь", "transliteration": "Skoraya pomoshch", "hebrew": "אמבולנס" },
    { "russian": "Опасность", "transliteration": "Opasnost", "hebrew": "סכנה" },
    { "russian": "Помощь", "transliteration": "Pomoshch", "hebrew": "עזרה" },
    { "russian": "Свобода", "transliteration": "Svoboda", "hebrew": "חופש" },
    { "russian": "Мир", "transliteration": "Mir", "hebrew": "שלום (לא מלחמה)" },
    { "russian": "Война", "transliteration": "Voyna", "hebrew": "מלחמה" },
    { "russian": "Армия", "transliteration": "Armiya", "hebrew": "צבא" },
    { "russian": "Солдат", "transliteration": "Soldat", "hebrew": "חייל" },
    { "russian": "Оружие", "transliteration": "Oruzhie", "hebrew": "נשק" },
    { "russian": "Победа", "transliteration": "Pobeda", "hebrew": "ניצחון" },
    { "russian": "История", "transliteration": "Istoriya", "hebrew": "היסטוריה" },
    { "russian": "Новости", "transliteration": "Novosti", "hebrew": "חדשות" },
    { "russian": "Газета", "transliteration": "Gazeta", "hebrew": "עיתון" },
    { "russian": "Журнал", "transliteration": "Zhurnal", "hebrew": "מגזין" },
    { "russian": "Радио", "transliteration": "Radio", "hebrew": "רדיו" },
    { "russian": "Телевизор", "transliteration": "Televizor", "hebrew": "טלוויזיה" },
    { "russian": "Интернет", "transliteration": "Internet", "hebrew": "אינטרנט" },
    { "russian": "Компьютер", "transliteration": "Kompyuter", "hebrew": "מחשב" },
    { "russian": "Телефон", "transliteration": "Telefon", "hebrew": "טלפון" },
    { "russian": "Фильм", "transliteration": "Film", "hebrew": "סרט" },
    { "russian": "Музыка", "transliteration": "Muzyka", "hebrew": "מוזיקה" },
    { "russian": "Песня", "transliteration": "Pesnya", "hebrew": "שיר" },
    { "russian": "Картина", "transliteration": "Kartina", "hebrew": "תמונה (ציור)" },
    { "russian": "Фотография", "transliteration": "Fotografiya", "hebrew": "צילום" },
    { "russian": "Камера", "transliteration": "Kamera", "hebrew": "מצלמה" },
    { "russian": "Спорт", "transliteration": "Sport", "hebrew": "ספורט" },
    { "russian": "Футбол", "transliteration": "Futbol", "hebrew": "כדורגל" },
    { "russian": "Мяч", "transliteration": "Myach", "hebrew": "כדור" },
    { "russian": "Команда", "transliteration": "Komanda", "hebrew": "קבוצה" },
    { "russian": "Игра", "transliteration": "Igra", "hebrew": "משחק" },
    { "russian": "Парк", "transliteration": "Park", "hebrew": "פארק" },
    { "russian": "Сад", "transliteration": "Sad", "hebrew": "גן" },
    { "russian": "Цвет", "transliteration": "Tsvet", "hebrew": "צבע" },
    { "russian": "Свет", "transliteration": "Svet", "hebrew": "אור" },
    { "russian": "Тень", "transliteration": "Ten", "hebrew": "צל" },
    { "russian": "Темнота", "transliteration": "Temnota", "hebrew": "חושך" },
    { "russian": "Утро", "transliteration": "Utro", "hebrew": "בוקר" },
    { "russian": "Вечер", "transliteration": "Vecher", "hebrew": "ערב" },
    { "russian": "Полдень", "transliteration": "Polden", "hebrew": "צהריים" },
    { "russian": "Полночь", "transliteration": "Polnoch", "hebrew": "חצות" },
    { "russian": "Час", "transliteration": "Chas", "hebrew": "שעה" },
    { "russian": "Минута", "transliteration": "Minuta", "hebrew": "דקה" },
    { "russian": "Секунда", "transliteration": "Sekunda", "hebrew": "שנייה" },
    { "russian": "Вопрос", "transliteration": "Vopros", "hebrew": "שאלה" },
    { "russian": "Ответ", "transliteration": "Otvet", "hebrew": "תשובה" },
    { "russian": "Проблема", "transliteration": "Problema", "hebrew": "בעיה" },
    { "russian": "Решение", "transliteration": "Reshenie", "hebrew": "פתרון" },
    { "russian": "Идея", "transliteration": "Ideya", "hebrew": "רעיון" },
    { "russian": "План", "transliteration": "Plan", "hebrew": "תוכנית" },
    { "russian": "Цель", "transliteration": "Tsel", "hebrew": "מטרה" },
    { "russian": "Успех", "transliteration": "Uspekh", "hebrew": "הצלחה" },
    { "russian": "Удача", "transliteration": "Udacha", "hebrew": "מזל" },
    { "russian": "Ошибка", "transliteration": "Oshibka", "hebrew": "טעות" },
    { "russian": "Правда", "transliteration": "Pravda", "hebrew": "אמת" },
    { "russian": "Ложь", "transliteration": "Lozh", "hebrew": "שקר" },
    { "russian": "Шутка", "transliteration": "Shutka", "hebrew": "בדיחה" },
    { "russian": "Секрет", "transliteration": "Sekret", "hebrew": "סוד" },
    { "russian": "Сюрприз", "transliteration": "Syurpriz", "hebrew": "הפתעה" },
    { "russian": "Подарок", "transliteration": "Podarok", "hebrew": "מתנה" },
    { "russian": "Бесплатно", "transliteration": "Besplatno", "hebrew": "חינם" },
    { "russian": "Важно", "transliteration": "Vazhno", "hebrew": "חשוב" },
    { "russian": "Интересно", "transliteration": "Interesno", "hebrew": "מעניין" },
    { "russian": "Скучно", "transliteration": "Skuchno", "hebrew": "משעמם" },
    { "russian": "Красиво", "transliteration": "Krasivo", "hebrew": "יפה" },
    { "russian": "Ужасно", "transliteration": "Uzhasno", "hebrew": "נורא" },
    { "russian": "Легко", "transliteration": "Legko", "hebrew": "קל" },
    { "russian": "Трудно", "transliteration": "Trudno", "hebrew": "קשה" },
    { "russian": "Быстро", "transliteration": "Bystro", "hebrew": "מהר" },
    { "russian": "Медленно", "transliteration": "Medlenno", "hebrew": "לאט" },
    { "russian": "Громко", "transliteration": "Gromko", "hebrew": "רועש / בקול רם" },
    { "russian": "Тихо", "transliteration": "Tikho", "hebrew": "שקט" },
    { "russian": "Чисто", "transliteration": "Chisto", "hebrew": "נקי" },
    { "russian": "Грязно", "transliteration": "Gryazno", "hebrew": "מלוכלך" },
    { "russian": "Полный", "transliteration": "Polny", "hebrew": "מלא" },
    { "russian": "Пустой", "transliteration": "Pustoy", "hebrew": "ריק" }
];

const russianWordEl = document.getElementById('russianWord');
const transliterationEl = document.getElementById('transliteration');
const hebrewTranslationEl = document.getElementById('hebrewTranslation');
const nextBtn = document.getElementById('nextBtn');
const speakBtn = document.getElementById('speakBtn');
const voiceStatusEl = document.getElementById('voiceStatus');

let currentWord = null;

function getNextWord() {
    const randomIndex = Math.floor(Math.random() * words.length);
    currentWord = words[randomIndex];
    displayWord();
}

function displayWord() {
    if (!currentWord) return;
    russianWordEl.textContent = currentWord.russian;
    transliterationEl.textContent = currentWord.transliteration;
    hebrewTranslationEl.textContent = currentWord.hebrew;
}

function speak() {
    if (!currentWord) return;

    // Check if browser supports speech synthesis
    if (!('speechSynthesis' in window)) {
        voiceStatusEl.textContent = "Your browser does not support Speech Synthesis.";
        return;
    }

    const text = currentWord.russian;
    const utterance = new SpeechSynthesisUtterance(text);

    // Try to find a Russian voice
    const voices = window.speechSynthesis.getVoices();
    const russianVoice = voices.find(voice => voice.lang.includes('ru'));

    if (russianVoice) {
        utterance.voice = russianVoice;
        voiceStatusEl.textContent = "";
    } else {
        voiceStatusEl.textContent = "Russian voice not found. Using default voice.";
        console.warn("Russian voice not found.");
        // We still speak, but it might sound wrong. 
        // Just like the Python script warning.
    }

    window.speechSynthesis.speak(utterance);
}

// Event Listeners
nextBtn.addEventListener('click', getNextWord);
speakBtn.addEventListener('click', speak);

// Initialize
// We need to wait for voices to load in some browsers
window.speechSynthesis.onvoiceschanged = () => {
    // Voices loaded
};

// Start with a word
getNextWord();
